SB - 123 [BE] Create table schemas
BFT-Smartbus/smartbus-backend pull request #15
Opened 2023-01-29 15:09 UTC by tonyxuan2021

![Screen Shot 2023-01-29 at 7 03 17 AM](https://user-images.githubusercontent.com/93957228/215335211-aff38b8b-8c35-485e-a661-3097138505d0.png)

- Created table models as per RDS 
- Connected to RDS (by making a query to the "/route-details/<string:route_id>" endpoint
- Enum data type was replaced by string because enum option (ie. cancelled) was already set up with RDS, tested with random string input and was prevented. Only predetermined enum options were allowed, therefore safe to use string data type.  
- Git stashed Aaron's testing code (ie. get all riders endpoint for RDS connection testing purpose)

2023-01-29 21:11 UTC, chunloy requested changes
Good work on this Tony. I noticed there aren't any foreign keys in the models that need them. Can we add them as well? Have a look at the `db_v1.sql` file in the DB repo (specifically lines 143 - 159).

2023-01-29 21:11 UTC, chunloy commented on models/Rider_route_requests.py
> +    pickup_lat: Decimal = db.Column(db.Numeric(9, 6))
Question: do you think it's necessary to have high precision? I would think 2-3 decimals would be enough. To my understanding, precision refers to the total number of digits, and scale refers to the number decimals. 

Longitude coordinates range from +/-180, so maybe we could set it to `Numeric(5, 2)` or `Numeric(6, 3)`. 

Similarly, latitudes range from +/- 90, so maybe set it to `Numeric(5, 3)` or `Numeric(4, 2)`.

2023-01-30 02:29 UTC, yhus commented on app.py
> +        return e.args[0], 400
Use a more detailed error message here. e.g. "Failed to write routes data to database"

2023-01-30 02:29 UTC, yhus commented on app.py
> +    route_data = Routes(
This part is business logic and should be factored out

2023-01-30 02:29 UTC, yhus commented on app.py
> +@app.route("/rider-details", methods=["POST"])
Is this just for testing? If so, please leave a comment making that clear, or remove it if it's not needed

2023-01-30 02:29 UTC, yhus commented on app.py
> +    return Routes.query.filter_by(route_id=routeId).one_or_none()
Wrap with try catch, and proper exception handling error message.

Also, "business logic" should be moved out of app.py, into e.g. routes.py for this specific case

2023-02-03 17:57 UTC, tonyxuan2021 commented on models/Routes.py
> +import enum
removed.

2023-02-03 18:00 UTC, tonyxuan2021 commented on models/Rider_route_requests.py
> +    pickup_lat: Decimal = db.Column(db.Numeric(9, 6))
Changed long to Numeric(6, 3), lat to Numeric(4, 2)

2023-02-03 18:40 UTC, yhus commented on models/Rider_route_requests.py
> +    pickup_lat: Decimal = db.Column(db.Numeric(9, 6))
http://wiki.gis.com/wiki/index.php/Decimal_degrees

For our use case I think we'd want at least 6  decimal places

2023-02-04 01:02 UTC, tonyxuan2021 commented on models/Rider_route_requests.py
> +    pickup_lat: Decimal = db.Column(db.Numeric(9, 6))
Changed both lat and long to Numeric(8,6), indicating max 2 digit number with 6 decimal places.

2023-02-09 23:03 UTC, tonyxuan2021 commented on app.py
> +        return e.args[0], 400
Changed to "Failed to write routes data to database" under line 91.

2023-02-09 23:24 UTC, tonyxuan2021 commented on app.py
> +    route_data = Routes(
Factored business logic (everything below line 76) to a helper function "handle_write_to_route_table".

2023-02-09 23:27 UTC, tonyxuan2021 commented on app.py
> +@app.route("/rider-details", methods=["POST"])
Deleted "rider-details" both GET and POST endpoint since it was for testing use only.

2023-02-10 06:43 UTC, yhus approved these changes

2023-02-10 16:03 UTC, StudentCZ approved these changes
I saw you were missing a try/except for one of the endpoint functions but overall your table schemas looks good.

2023-02-11 07:10 UTC, chunloy approved these changes
👍

2023-02-12 21:35 UTC, tonyxuan2021 commented
Resolved merge conflict and addressed all comments.

2023-02-12 21:35 UTC, merged